# Generated by Django 5.0.6 on 2024-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Headphones', 'Headphones'), ('Tablets', 'Tablets'), ('Networking', 'Networking'), ('PC Gaming', 'PC Gaming')], default='Laptops', max_length=50),
        ),
    ]
